export const weddingConfig = {
    brideName: "Anjali",
    groomName: "Rahul",
    weddingDate: "18",
    weddingDateSuffix: "th",
    weddingDay: "SATURDAY",
    weddingMonthYear: "DECEMBER 2026",
    weddingTime: "5:00 PM",
    venueName: "The Grand Taj Palace",
    venueAddress: "123 Royale Avenue, Udaipur, Rajasthan",
    mapsUrl: "https://maps.google.com",
    brideParents: "Mr. & Mrs. Sharma",
    groomParents: "Mr. & Mrs. Verma",
    rsvpUrl: "#rsvp",
    events: [
        {
            id: "mehendi",
            title: "Mehendi",
            icon: "🌿",
            date: "16 December 2026",
            time: "10:00 AM",
            venue: "Courtyard Gardens",
        },
        {
            id: "haldi",
            title: "Haldi",
            icon: "🌼",
            date: "17 December 2026",
            time: "11:00 AM",
            venue: "Poolside Pavilion",
        },
        {
            id: "wedding",
            title: "Wedding Ceremony",
            icon: "💍",
            date: "18 December 2026",
            time: "5:00 PM",
            venue: "Main Mandap, The Grand Taj Palace",
        },
        {
            id: "reception",
            title: "Reception",
            icon: "✨",
            date: "19 December 2026",
            time: "7:00 PM",
            venue: "The Royal Ballroom",
        },
    ]
};
