export const weddingConfig = {
    brideName: "Vranda",
    groomName: "Rahul",
    weddingDate: "22",
    weddingDateSuffix: "th",
    weddingDay: "SATURDAY",
    weddingMonthYear: "DECEMBER 2026",
    weddingTime: "5:00 PM",
    venueName: "The Grand Taj Palace",
    venueAddress: "123 Royale Avenue, Udaipur, Rajasthan",
    mapsUrl: "https://www.google.com/maps/place/PATRAM+HAWELI/@29.8980175,77.9936267,1695m/data=!3m1!1e3!4m9!3m8!1s0x39094bbddb109d69:0x14f184fbc633329c!5m2!4m1!1i2!8m2!3d29.9039491!4d77.9949479!16s%2Fg%2F11w940nvt8!5m1!1e2?entry=ttu&g_ep=EgoyMDI2MDkyOC4wIKXMDSoASAFQAw%3D%3D",
    brideParents: "Mr. & Mrs. Sharma",
    groomParents: "Mr. & Mrs. Verma",
    rsvpUrl: "#rsvp",
    events: [
        {
            id: "mehendi",
            title: "Mehendi",
            icon: "🌿",
            date: "16 December 2026",
            time: "10:00 AM",
            venue: "Courtyard Gardens",
        },
        {
            id: "haldi",
            title: "Haldi",
            icon: "🌼",
            date: "17 December 2026",
            time: "11:00 AM",
            venue: "Poolside Pavilion",
        },
        {
            id: "wedding",
            title: "Wedding Ceremony",
            icon: "💍",
            date: "18 December 2026",
            time: "5:00 PM",
            venue: "Main Mandap, The Grand Taj Palace",
        },
        {
            id: "reception",
            title: "Reception",
            icon: "✨",
            date: "19 December 2026",
            time: "7:00 PM",
            venue: "The Royal Ballroom",
        },
    ]
};
